-- =================================================================
-- Migration: Seed All Original iWAAT Static Projects into public.projects
-- Project: iBot (npqfnzuyglgrzsetrbdo)
-- =================================================================

INSERT INTO public.projects (
  id, title, slug, category, category_slug, url, tagline, description, long_description,
  image, preview_status, preview_source, preview_updated_at, featured, status,
  completion_date, display_order, stats, technologies, highlights, client_name
)
VALUES
  (
    'chinmaya-mission-healthcare-ngo',
    'Chinmaya Mission Healthcare & NGO Portal',
    'chinmaya-mission-healthcare-ngo',
    'Healthcare',
    'healthcare',
    'https://chinmaya-mission.vercel.app/',
    'Global healthcare initiative, medical outreach & spiritual organization portal',
    'A comprehensive healthcare and social welfare platform designed for global outreach, medical services showcases, patient-focused information architecture, responsive layouts, and trust-driven community engagement.',
    'The Chinmaya Mission Healthcare & NGO Portal bridges global community outreach with medical service programs. Built with accessibility, spiritual heritage, and medical trust as core pillars, the platform facilitates health camp registrations, rural medical aid, donation portals, and educational programs.',
    'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1200&auto=format&fit=crop',
    'ready',
    'original',
    NOW(),
    true,
    'published',
    '2026',
    1,
    '[{"label": "Global Reach", "value": "100K+"}, {"label": "Load Speed", "value": "0.5s"}, {"label": "User Trust Score", "value": "99.8%"}]'::JSONB,
    '["React 19", "Tailwind CSS", "Framer Motion", "Vite", "Lucide Icons"]'::JSONB,
    '["Rural health camp registration & schedule manager", "Frictionless donation portal interface", "Multi-category medical service showcase", "Accessible typography and responsive layout architecture"]'::JSONB,
    'Chinmaya Mission'
  ),
  (
    'narayan-ashram-platform',
    'Narayan Ashram Spiritual & Cultural Trust',
    'narayan-ashram-platform',
    'NGO & Nonprofit',
    'ngo-nonprofit',
    'https://narayan-ashram.vercel.app/',
    'Spiritual retreat, cultural heritage & community outreach platform',
    'A serene, modern cultural trust and ashram platform featuring spiritual discourses, event registrations, retreat bookings, social welfare initiatives, and digital donation portals.',
    'Engineered for Narayan Ashram to preserve spiritual heritage while providing modern digital access to retreat schedules, daily discourses, ashram stay bookings, and charitable community outreach programs.',
    'https://images.unsplash.com/photo-1545205597-3d9d02c29597?q=80&w=1200&auto=format&fit=crop',
    'ready',
    'original',
    NOW(),
    true,
    'published',
    '2026',
    2,
    '[{"label": "Monthly Visitors", "value": "35K+"}, {"label": "Event Signups", "value": "12K+"}, {"label": "Uptime Rating", "value": "99.9%"}]'::JSONB,
    '["React", "Tailwind CSS", "Framer Motion", "Vite", "Lucide Icons"]'::JSONB,
    '["Interactive retreat & event calendar registration", "Audio/Video discourse streaming section", "Charitable donation and anna-kshetra sponsorship portal", "Serene glassmorphism and golden warm aesthetic theme"]'::JSONB,
    'Narayan Ashram'
  ),
  (
    'wedding-photography-portfolio',
    'Wedding & Photography Portfolio',
    'wedding-photography-portfolio',
    'Photography',
    'photography',
    'https://photograpy-website-one.vercel.app/',
    'Cinematic visual storytelling & client booking experience',
    'An elegant photography portfolio and ceremony-focused website featuring immersive galleries, cinematic layouts, booking CTAs, responsive storytelling, and premium visual presentation.',
    'Crafted for visual artists and luxury event photographers, this platform presents high-resolution imagery through smooth parallax galleries and curated album storytelling. It includes an interactive pricing guide, inquiry portal, and client testimonial sliders.',
    'https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=1200&auto=format&fit=crop',
    'ready',
    'original',
    NOW(),
    true,
    'published',
    '2026',
    3,
    '[{"label": "Inquiry Conversion", "value": "+140%"}, {"label": "Gallery Views", "value": "120K+"}, {"label": "Mobile Engagement", "value": "4.8/5"}]'::JSONB,
    '["React", "Tailwind CSS", "Swiper.js", "Framer Motion", "Vercel"]'::JSONB,
    '["Fluid masonry photo gallery with lightbox view", "Cinematic dark/light aesthetic transition", "Automated booking enquiry form with date picker", "Optimized media loading with lazy blur placeholders"]'::JSONB,
    'Wedding Photography'
  ),
  (
    'luxury-jewelry-store',
    'Luxury Jewelry Store Experience',
    'luxury-jewelry-store',
    'Retail',
    'retail',
    '#',
    'High-end jewelry storefront with immersive product showcase',
    'A premium jewelry storefront experience with elegant product presentation, luxury branding, responsive design, and modern UI interactions.',
    'Designed to reflect the opulence and craftsmanship of fine jewelry, this digital storefront combines rich typography, gold-accented glassmorphism, 360 product view framing, and smooth micro-interactions that elevate brand prestige.',
    'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1200&auto=format&fit=crop',
    'ready',
    'original',
    NOW(),
    true,
    'published',
    '2026',
    4,
    '[{"label": "Brand Value Rating", "value": "9.9/10"}, {"label": "Average Order Value", "value": "+35%"}, {"label": "Customer Dwell Time", "value": "4m 12s"}]'::JSONB,
    '["React", "Tailwind CSS", "Framer Motion", "Lucide React", "Vite"]'::JSONB,
    '["High-definition gemstone & precious metal showcases", "Interactive collection filtering by metal, gem & style", "Bespoke custom order inquiry modal", "Ultra-sleek dark mode elegance design language"]'::JSONB,
    'Luxury Jewelry'
  ),
  (
    'pathology-laboratory',
    'Pathology Laboratory Portal',
    'pathology-laboratory',
    'Pathology & Diagnostic Labs',
    'pathology-diagnostic-labs',
    'https://patho-logy-labs.vercel.app/',
    'Diagnostic test booking & health package platform',
    'A professional pathology and diagnostics center website featuring test listings, healthcare services, appointment-focused UI, responsive layouts, and medical credibility design patterns.',
    'Built to streamline medical diagnostics for patients and clinical partners. The platform facilitates home blood collection scheduling, lab report downloads, package comparisons, and instant WhatsApp support.',
    'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=1200&auto=format&fit=crop',
    'ready',
    'original',
    NOW(),
    true,
    'published',
    '2026',
    5,
    '[{"label": "Test Bookings", "value": "15K+"}, {"label": "Report Download Time", "value": "<1 sec"}, {"label": "SEO Rank (Top 3)", "value": "92%"}]'::JSONB,
    '["React 19", "Tailwind CSS", "Vite", "Lucide Icons", "React Hook Form"]'::JSONB,
    '["Comprehensive diagnostic test catalog with search & filter", "One-click home sample collection booking", "Patient report download portal simulation", "Trust badges and accredited laboratory certification displays"]'::JSONB,
    'Pathology Laboratory'
  ),
  (
    'gym-fitness-platform',
    'Gym & Fitness Growth Platform',
    'gym-fitness-platform',
    'Sports & Fitness',
    'sports-fitness',
    'https://gym-website-two-lac.vercel.app/',
    'High-energy athletic membership & training platform',
    'A high-energy fitness platform showcasing membership plans, trainers, workout programs, responsive animations, and strong conversion-focused design.',
    'Designed to motivate fitness enthusiasts and drive gym membership signups. Features vibrant neon energy accents, interactive class schedules, trainer bio cards, transformational video stories, and transparent pricing matrices.',
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1200&auto=format&fit=crop',
    'ready',
    'original',
    NOW(),
    true,
    'published',
    '2026',
    6,
    '[{"label": "Membership Conversions", "value": "+210%"}, {"label": "Active Trainees", "value": "2.5K+"}, {"label": "Mobile Traffic", "value": "78%"}]'::JSONB,
    '["React", "Tailwind CSS", "Framer Motion", "Swiper", "React CountUp"]'::JSONB,
    '["Dynamic workout schedule matrix by day and discipline", "Interactive BMI calculator widget", "Trainer profile highlights with specialization badges", "High-energy neon dark mode aesthetic"]'::JSONB,
    'Gym & Fitness'
  ),
  (
    'ngo-organization-portal',
    'NGO Social Impact Portal',
    'ngo-organization-portal',
    'NGO & Nonprofit',
    'ngo-nonprofit',
    'https://ngo-project-nu.vercel.app/',
    'Empowering global initiatives, donations & community engagement',
    'A modern nonprofit and social impact website designed for awareness, donations, volunteer engagement, healthcare initiatives, and educational outreach.',
    'Created to amplify non-profit missions, drive global campaign transparency, and enable frictionless community support. Highlights active social causes, transparent funding reports, volunteer enrollment forms, and real-time impact counters.',
    'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=1200&auto=format&fit=crop',
    'ready',
    'original',
    NOW(),
    true,
    'published',
    '2026',
    7,
    '[{"label": "Donations Raised", "value": "$1.2M+"}, {"label": "Volunteers Joined", "value": "5K+"}, {"label": "Impact Score", "value": "100%"}]'::JSONB,
    '["React", "Tailwind CSS", "Framer Motion", "Lucide React", "Vite"]'::JSONB,
    '["Campaign transparency meters with dynamic progress bars", "Frictionless online donation experience interface", "Volunteer onboarding registration modal", "Storytelling blog and disaster relief emergency response banners"]'::JSONB,
    'NGO Organization'
  )
ON CONFLICT (id) DO NOTHING;
